// <auto-generated />
using System;
using Dal;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Dal.Migrations
{
    [DbContext(typeof(RegistryContext))]
    partial class RegistryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Domain.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK_dbo.Countries");

                    b.ToTable("Countries", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Afghanistan"
                        },
                        new
                        {
                            Id = 2,
                            Name = "France"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Greece"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Hungary"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Tanzania"
                        });
                });

            modelBuilder.Entity("Domain.Province", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK_dbo.Provinces");

                    b.HasIndex(new[] { "CountryId" }, "IX_CountryId");

                    b.ToTable("Provinces");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CountryId = 1,
                            Name = "Badakhshan"
                        },
                        new
                        {
                            Id = 2,
                            CountryId = 1,
                            Name = "Farah"
                        },
                        new
                        {
                            Id = 3,
                            CountryId = 1,
                            Name = "Ghazni"
                        },
                        new
                        {
                            Id = 4,
                            CountryId = 1,
                            Name = "Ghōr"
                        },
                        new
                        {
                            Id = 5,
                            CountryId = 2,
                            Name = "Métropole de Lyon"
                        },
                        new
                        {
                            Id = 6,
                            CountryId = 2,
                            Name = "Normandie"
                        },
                        new
                        {
                            Id = 7,
                            CountryId = 4,
                            Name = "Nógrád County"
                        },
                        new
                        {
                            Id = 8,
                            CountryId = 4,
                            Name = "Pécs"
                        },
                        new
                        {
                            Id = 9,
                            CountryId = 4,
                            Name = "Somogy County"
                        },
                        new
                        {
                            Id = 10,
                            CountryId = 5,
                            Name = "Shinyanga"
                        });
                });

            modelBuilder.Entity("Domain.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("Agreed")
                        .HasColumnType("bit");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProvinceId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK_dbo.Users");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex(new[] { "CountryId" }, "IX_CountryId")
                        .HasDatabaseName("IX_CountryId1");

                    b.HasIndex(new[] { "ProvinceId" }, "IX_ProvinceId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Domain.Province", b =>
                {
                    b.HasOne("Domain.Country", "Country")
                        .WithMany("Provinces")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_dbo.Provinces_dbo.CountryId");

                    b.Navigation("Country");
                });

            modelBuilder.Entity("Domain.User", b =>
                {
                    b.HasOne("Domain.Country", "Country")
                        .WithMany("Users")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_dbo.Users_dbo.CountryId");

                    b.HasOne("Domain.Province", "Province")
                        .WithMany("Users")
                        .HasForeignKey("ProvinceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_dbo.Users_dbo.ProvinceId");

                    b.Navigation("Country");

                    b.Navigation("Province");
                });

            modelBuilder.Entity("Domain.Country", b =>
                {
                    b.Navigation("Provinces");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Domain.Province", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
